# scikit learn

In [115]:
from sklearn.linear_model import LinearRegression

import pandas as pd
import numpy as np
import matplotlib as plt

from sklearn.model_selection import train_test_split

from sklearn.metrics import r2_score,root_mean_squared_error

In [116]:
df=pd.read_csv(r"C:\artificial_intelligence_coarse\kc_house_data.csv")

In [117]:
df.head(5)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [118]:
df.size

453873

In [119]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  str
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), str(1)
memory usage: 3.5 MB

In [120]:
df=df.drop(columns=['id','date'])

In [121]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 19 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          21613 non-null  float64
 1   bedrooms       21613 non-null  int64
 2   bathrooms      21613 non-null  float64
 3   sqft_living    21613 non-null  int64
 4   sqft_lot       21613 non-null  int64
 5   floors         21613 non-null  float64
 6   waterfront     21613 non-null  int64
 7   view           21613 non-null  int64
 8   condition      21613 non-null  int64
 9   grade          21613 non-null  int64
 10  sqft_above     21613 non-null  int64
 11  sqft_basement  21613 non-null  int64
 12  yr_built       21613 non-null  int64
 13  yr_renovated   21613 non-null  int64
 14  zipcode        21613 non-null  int64
 15  lat            21613 non-null  float64
 16  long           21613 non-null  float64
 17  sqft_living15  21613 non-null  int64
 18  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(14)
memory usage: 3.1 MB

In [122]:
df.corr()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
price,1.000000,0.308350,0.525138,0.702035,0.089661,0.256794,0.266369,0.397293,0.036362,0.667434,0.605567,0.323816,0.054012,0.126434,-0.053203,0.307003,0.021626,0.585379,0.082447
bedrooms,0.308350,1.000000,0.515884,0.576671,0.031703,0.175429,-0.006582,0.079532,0.028472,0.356967,0.477600,0.303093,0.154178,0.018841,-0.152668,-0.008931,0.129473,0.391638,0.029244
bathrooms,0.525138,0.515884,1.000000,0.754665,0.087740,0.500653,0.063744,0.187737,-0.124982,0.664983,0.685342,0.283770,0.506019,0.050739,-0.203866,0.024573,0.223042,0.568634,0.087175
sqft_living,0.702035,0.576671,0.754665,1.000000,0.172826,0.353949,0.103818,0.284611,-0.058753,0.762704,0.876597,0.435043,0.318049,0.055363,-0.199430,0.052529,0.240223,0.756420,0.183286
sqft_lot,0.089661,0.031703,0.087740,0.172826,1.000000,-0.005201,0.021604,0.074710,-0.008958,0.113621,0.183512,0.015286,0.053080,0.007644,-0.129574,-0.085683,0.229521,0.144608,0.718557
floors,0.256794,0.175429,0.500653,0.353949,-0.005201,1.000000,0.023698,0.029444,-0.263768,0.458183,0.523885,-0.245705,0.489319,0.006338,-0.059121,0.049614,0.125419,0.279885,-0.011269
waterfront,0.266369,-0.006582,0.063744,0.103818,0.021604,0.023698,1.000000,0.401857,0.016653,0.082775,0.072075,0.080588,-0.026161,0.092885,0.030285,-0.014274,-0.041910,0.086463,0.030703
view,0.397293,0.079532,0.187737,0.284611,0.074710,0.029444,0.401857,1.000000,0.045990,0.251321,0.167649,0.276947,-0.053440,0.103917,0.084827,0.006157,-0.078400,0.280439,0.072575
condition,0.036362,0.028472,-0.124982,-0.058753,-0.008958,-0.263768,0.016653,0.045990,1.000000,-0.144674,-0.158214,0.174105,-0.361417,-0.060618,0.003026,-0.014941,-0.106500,-0.092824,-0.003406
grade,0.667434,0.356967,0.664983,0.762704,0.113621,0.458183,0.082775,0.251321,-0.144674,1.000000,0.755923,0.168392,0.446963,0.014414,-0.184862,0.114084,0.198372,0.713202,0.119248
sqft_above,0.605567,0.477600,0.685342,0.876597,0.183512,0.523885,0.072075,0.167649,-0.158214,0.755923,1.000000,-0.051943,0.423898,0.023285,-0.261190,-0.000816,0.343803,0.731870,0.194050
sqft_basement,0.323816,0.303093,0.283770,0.435043,0.015286,-0.245705,0.080588,0.276947,0.174105,0.168392,-0.051943,1.000000,-0.133124,0.071323,0.074845,0.110538,-0.144765,0.200355,0.017276
yr_built,0.054012,0.154178,0.506019,0.318049,0.053080,0.489319,-0.026161,-0.053440,-0.361417,0.446963,0.423898,-0.133124,1.000000,-0.224874,-0.346869,-0.148122,0.409356,0.326229,0.070958
yr_renovated,0.126434,0.018841,0.050739,0.055363,0.007644,0.006338,0.092885,0.103917,-0.060618,0.014414,0.023285,0.071323,-0.224874,1.000000,0.064357,0.029398,-0.068372,-0.002673,0.007854
zipcode,-0.053203,-0.152668,-0.203866,-0.199430,-0.129574,-0.059121,0.030285,0.084827,0.003026,-0.184862,-0.261190,0.074845,-0.346869,0.064357,1.000000,0.267048,-0.564072,-0.279033,-0.147221
lat,0.307003,-0.008931,0.024573,0.052529,-0.085683,0.049614,-0.014274,0.006157,-0.014941,0.114084,-0.000816,0.110538,-0.148122,0.029398,0.267048,1.000000,-0.135512,0.048858,-0.086419
long,0.021626,0.129473,0.223042,0.240223,0.229521,0.125419,-0.041910,-0.078400,-0.106500,0.198372,0.343803,-0.144765,0.409356,-0.068372,-0.564072,-0.135512,1.000000,0.334605,0.254451
sqft_living15,0.585379,0.391638,0.568634,0.756420,0.144608,0.279885,0.086463,0.280439,-0.092824,0.713202,0.731870,0.200355,0.326229,-0.002673,-0.279033,0.048858,0.334605,1.000000,0.183192
sqft_lot15,0.082447,0.029244,0.087175,0.183286,0.718557,-0.011269,0.030703,0.072575,-0.003406,0.119248,0.194050,0.017276,0.070958,0.007854,-0.147221,-0.086419,0.254451,0.183192,1.000000

In [123]:
Y=df['price']

In [124]:
df.corr()['price'].sort_values(ascending=False).drop('price')

sqft_living      0.702035
grade            0.667434
sqft_above       0.605567
sqft_living15    0.585379
bathrooms        0.525138
view             0.397293
sqft_basement    0.323816
bedrooms         0.308350
lat              0.307003
waterfront       0.266369
floors           0.256794
yr_renovated     0.126434
sqft_lot         0.089661
sqft_lot15       0.082447
yr_built         0.054012
condition        0.036362
long             0.021626
zipcode         -0.053203
Name: price, dtype: float64

In [125]:
feature=['sqft_living','grade','sqft_above','sqft_living15','bathrooms','view','bedrooms','lat','waterfront','floors']

In [126]:
X = df[feature]

In [127]:
x_train,x_test,y_trian,y_test=train_test_split(X,Y,test_size=0.2,random_state=(42))

In [128]:
house_price=LinearRegression()

In [129]:
house_price.fit(x_train,y_trian)

LinearRegression()

In [130]:
y_prediction=house_price.predict(x_test)

In [131]:
len(df)*0.2

4322.6

In [132]:
y_test

735       365000.0
2830      865000.0
4106     1038000.0
16218    1490000.0
19964     711000.0
           ...
13674     338000.0
20377     673000.0
8805      285000.0
10168     605000.0
2522      356500.0
Name: price, Length: 4323, dtype: float64

In [133]:
r2_score(y_true=y_test,y_pred=y_prediction)

0.6614781405487573

In [134]:
root_mean_squared_error(y_test,y_prediction)

226222.50493466947

In [135]:
house_price.intercept_

np.float64(-32299223.00482296)

In [136]:
house_price.coef_

array([ 1.92290574e+02,  8.00263262e+04,  1.39782556e+00,  3.35505098e+00,
       -5.26090513e+02,  6.85711779e+04, -2.39310851e+04,  6.71230692e+05,
        5.84624181e+05, -3.05952288e+04])

In [137]:
df2=pd.read_csv(r"C:\artificial_intelligence_coarse\sir_git_ai\Artificial-Inteligence-Machine-Learning-and-Deep-Learning-NAVTTC-Course-2026\week-06-regression-and-classification-ML\datasets\laptop_prices.csv")

In [138]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ram_gb       1200 non-null   int64
 1   storage_gb   1200 non-null   int64
 2   screen_size  1200 non-null   float64
 3   weight_kg    1200 non-null   float64
 4   cpu_score    1200 non-null   int64
 5   gpu_score    1200 non-null   int64
 6   age_years    1200 non-null   int64
 7   price        1200 non-null   float64
dtypes: float64(3), int64(5)
memory usage: 75.1 KB

In [139]:
df2.head()

,ram_gb,storage_gb,screen_size,weight_kg,cpu_score,gpu_score,age_years,price
0,16,256,12.0,1.80,5381,3209,3,912.0
1,32,1024,12.5,1.38,12751,13736,5,1990.0
2,16,256,14.8,2.06,3634,7953,5,1094.0
3,8,1024,16.9,2.41,8392,2067,2,1084.0
4,8,1024,14.0,2.31,22301,19385,1,2068.0

In [140]:
y2=df2['price']
y2

0        912.0
1       1990.0
2       1094.0
3       1084.0
4       2068.0
         ...
1195    1977.0
1196    1286.0
1197    2018.0
1198    1131.0
1199    1670.0
Name: price, Length: 1200, dtype: float64

In [141]:
df2.corr()['price'].sort_values(ascending=False).drop('price')

ram_gb         0.778689
gpu_score      0.432267
cpu_score      0.230264
storage_gb     0.154518
screen_size    0.153477
weight_kg      0.040739
age_years     -0.253912
Name: price, dtype: float64

In [142]:
feature2=['ram_gb','gpu_score','storage_gb','screen_size','age_years']

In [143]:
X2=df2[feature2]

In [144]:
X2

      ram_gb  gpu_score  storage_gb  screen_size  age_years
0         16       3209         256         12.0          3
1         32      13736        1024         12.5          5
2         16       7953         256         14.8          5
3          8       2067        1024         16.9          2
4          8      19385        1024         14.0          1
...      ...        ...         ...          ...        ...
1195      16      18519         256         12.9          4
1196       8       2511         256         14.4          2
1197      32       5017        1024         14.8          2
1198       4      15688         512         13.6          2
1199       8       6928        1024         16.5          2

[1200 rows x 5 columns]

In [150]:
x_train2,x_test2,y_train2,y_test2=train_test_split(X2, y2,train_size=0.2,random_state=42)

In [151]:
laptop_rs_pred=LinearRegression()

In [152]:
laptop_rs_pred.fit(x_train2,y_train2)

LinearRegression()

In [153]:
laptop_rs_pred.predict(x_test2)

array([1471.62082301, 1559.88023048, 1576.59130015,  838.64220634,
       2361.15877266, 1829.45040131, 1949.61773411, 1277.97483282,
       1535.46025152,  971.72861019, 1195.78089834, 1524.82578859,
       1939.16221428,  934.75047112,  986.44950404, 1272.98471397,
       1428.30187458, 1456.86183411, 1193.10827769, 1443.66898661,
       1719.7761221 , 1700.31869576, 1232.1072853 , 1492.84231083,
       1542.08273991, 1544.49931896, 1713.11099153, 2075.10559552,
       1349.99335579, 1416.96782647, 1537.18638057, 1190.18454175,
       1540.34654394, 2019.2335132 , 1731.63335476, 1274.19539406,
       1334.31833289, 1513.50463596, 1108.80267078, 1305.50501505,
       1107.49051273, 1487.89404777, 1429.88708119, 1383.62525686,
       1966.28311597, 1777.13506252, 1046.33043707, 1375.13264496,
       1985.71523081, 1830.2417099 , 1665.01102141, 1020.04168078,
       1658.28745671, 1340.41642556, 1631.79809493, 1870.04301289,
       1096.76082893, 1452.26566866, 2020.78095329, 1677.96756094,
       2029.85208111, 3030.7977833 , 1573.48022929, 1223.86768588,
       1631.51436825, 2381.5796489 , 1452.13616018, 1505.00663461,
       1011.85785104, 1082.83402033, 2941.7372798 , 1606.87983485,
       1572.73184328, 1540.44717245, 1593.28615021, 1570.32295902,
       2271.25403196, 2271.7884855 , 2294.31872785, 2504.33213999,
       1537.61206578, 1126.18016368, 1188.56799084, 2026.94215183,
        878.94334394, 1321.63639111, 1630.05158812, 1606.62484845,
       1431.45507429, 2087.59859255, 1291.72478832, 1818.35325208,
       1264.50423087, 1565.61725897, 1361.09284153, 1247.04289745,
       1225.14833066, 1447.40384552, 1119.48597776, 1375.64093474,
       1109.56256933, 1439.3077303 , 1130.23360289, 1629.47544238,
       1402.46981823, 1498.99059689, 1553.16401747, 1149.73843405,
       1475.6890842 , 2870.61764535, 1415.0474673 , 1356.49862474,
       1240.72248472, 1101.56149878, 1130.84375616, 1478.23989983,
        941.28274859, 1856.04987956, 1126.88984155, 1606.46458265,
       1255.89235721, 2086.17133156, 1179.76451173, 1879.3499242 ,
       1616.1470433 ,  961.2498275 , 2437.60360845, 1787.28993435,
       1546.50316442, 1496.52020234, 1733.58209908, 1302.84764339,
       1201.43793645, 1967.81301406, 2351.71258979, 1834.96714951,
       1601.11571673, 1056.67518226,  972.44132595, 1530.03520653,
       1602.97137646, 1926.47026057, 1077.49442176, 1341.66618276,
       1630.35381266, 1551.45164439, 1569.85649851, 1386.83102528,
       1536.85640769, 1393.92350404, 1139.61140032, 1398.43602521,
       1572.7611269 , 1130.54217799, 1824.17937173, 1555.45845424,
       1627.71164527, 1540.68146017, 1679.00630315, 1330.63533728,
       1532.14831979, 1365.34083786, 2073.04316171, 1733.3680882 ,
       1305.0761426 , 1997.08609508, 1045.87316442, 1419.36175383,
       1542.51821544, 1650.4657797 , 1604.14466248, 1715.98778887,
       1601.66686286, 1956.00482572, 1636.9523812 , 1186.31118046,
       1341.62747064, 1473.21954492, 1486.2923405 , 1313.69334325,
       1286.61164567, 1378.36462868, 1776.34888106, 1435.91760948,
       1687.38066179, 1532.86716051, 1407.68473925, 1449.36922664,
       1808.37121499, 1216.39731965, 1474.87638821, 1436.71749196,
       1357.29738112, 1592.26904276, 1561.9511183 , 2002.04265304,
       1631.8484394 , 1108.19942979, 1942.65453703, 1578.84828512,
       1682.4324176 , 2239.34042466, 1499.51619668, 1053.97472499,
       1624.44378274, 2070.96690145,  860.72346205, 1048.89629712,
       1839.97817089, 1079.07058306, 1072.99684169, 1681.20256943,
       1607.2003919 , 1673.96168879, 1069.20884919, 1176.16733222,
       2042.74034537, 1724.33921388, 1494.53383197, 1434.43998085,
       1014.27470802, 1867.03514307, 1361.78695966, 2137.22588359,
       1197.02181969, 1186.43156846, 2453.49956112, 1796.8831154 ,
       1320.38827697, 1340.34204872, 1427.97098502, 1063.4780284 ,
       1428.94938307, 1726.53320854, 1437.00824835, 1284.39646033,
       1421.80699238, 1371.3177284 , 1217.03325316, 1194.80206926,
       1330.06719655, 2088.62903888, 1849.57539769, 1242.2413302 ,
       2061.65096853, 2078.04111422, 2096.78448899, 1304.12113641,
       1654.07566464, 1614.25114634, 1700.78140541, 1030.50121548,
       2060.06804818, 1961.78217624, 1396.06291924, 1341.92792824,
       1638.75978071, 2122.97506722, 1786.87247907, 1990.69886365,
       1342.37768814, 1348.77772712, 1554.11590378, 1258.3924831 ,
       2170.5303597 , 1732.9796968 , 1500.87567484,  901.59312586,
       1761.72259876, 1495.86019571, 1601.14397724, 1505.64177764,
       1895.88338666, 1795.94159332, 2012.90388576, 1308.53859106,
       1315.82452421, 1617.57660842, 1651.22947263, 3010.64084339,
       2381.03210979, 1212.90205278, 1282.04271   , 1396.02245836,
       1371.82936552, 1055.55313336, 1698.62847729, 1468.97081918,
       2895.28118221, 1369.59833223, 1687.52820821, 1767.61509623,
        802.61893494, 1982.36116652, 2775.60329485, 1452.91085451,
       1593.61232751, 1210.76584332, 2670.58097379, 1396.92166834,
       1446.00672831, 1939.82120826, 1360.59817132, 1875.33978318,
       1257.05808813, 2796.19736013, 1448.14592537, 1707.53686895,
       1011.3534151 , 1347.55080369, 1178.72854176, 1120.98827905,
       1567.65466338, 1476.36776521, 1200.36674115, 1430.39536102,
       1126.37412067, 1354.53360982, 1542.77578099, 1632.26775273,
       1218.19400903, 1259.23188325, 2428.22204912, 1312.38876475,
       1138.14163122, 1535.66411629, 1447.83190614, 2075.09858748,
       1558.54409315, 1335.99563887, 3055.00903526, 1319.60709313,
       1260.2493113 , 1437.3957194 , 1160.97823191, 1317.18761782,
       1593.06184009, 1562.82675348, 1072.7649349 , 1977.82794794,
       2119.99295943, 1634.42207265, 1943.05071098, 1953.01445162,
       1431.81651062, 1429.64411552, 1317.05605222, 1208.13144081,
       1550.81502063, 2195.96658489, 1615.51096289, 1198.84207669,
       1540.71820908, 1772.10045802, 1561.28958223, 1915.69800612,
        991.79453247, 1849.9669041 , 1525.84505484, 1409.74564045,
       1462.96079203, 1580.54339875, 1058.20691055, 2228.34718987,
       1855.45283988, 1926.02516415, 1993.79850242, 2188.1381211 ,
       1304.17189741, 1021.46432699, 1343.97694962, 1175.13246465,
       1692.5430113 , 1304.63016666, 1006.38899536, 1456.40144312,
       1847.10654948, 1342.8992933 , 1343.79594668, 2099.84725331,
       1554.36700752, 2471.41691024, 1101.29337709, 1595.72733553,
       1447.27597651, 1530.99796167, 1646.1077454 , 1990.73169754,
       1135.65725264, 2829.96095142, 1945.90457523, 1147.73653686,
       2199.07855542, 1284.35920878, 1475.8133267 , 1789.81701848,
       1421.0625214 , 1424.90458583, 1918.28675421, 1343.36444162,
       1197.36261783, 1447.86423686, 2059.72511226, 1945.52801544,
       1581.84948018, 1882.64959695, 1640.29728047, 1941.94693445,
       1358.55789753, 1544.43889954, 1487.33223506, 1222.32733302,
       1344.21560561, 1587.93826714, 1268.7727236 , 3202.59879922,
       1484.36497295, 1778.94632088, 1479.68538099, 1573.14315629,
       1566.38968135, 1805.80910179, 2172.05494977, 1479.04515521,
       1548.12142737, 1446.93649368, 1777.00213209, 1029.00332634,
       1609.0731812 , 1248.70697904, 2020.02862952, 1438.88952326,
       1576.97624712, 1580.43717318, 1473.34237993, 2017.0844724 ,
       1910.46284401, 1703.03365475, 1646.87255962, 1532.81596728,
       1500.93987838, 1137.74988326, 1628.08242496, 1109.43759657,
       1153.11241325, 1145.76963224, 1478.85011918, 1377.5572145 ,
       1244.1530189 , 1565.78632316, 1585.46514055, 1211.63811723,
       1544.60121735, 1468.81248301, 2812.60626296, 1301.41866167,
       1311.79191787, 1443.42010144, 1811.20215918, 1640.26738721,
       1193.15281952, 1583.1614542 , 1996.71451905, 1238.20695616,
       2111.39390599, 1533.97841413, 1296.00968509, 1397.85333173,
        898.41788601, 1035.50248541, 2115.34541001, 1944.43337487,
       1737.94136964, 1291.85297042, 1253.33514782,  971.83667347,
       1686.96984663, 1257.24214368, 1429.67311343, 1120.8510932 ,
       1593.93118486, 1668.72382635, 1339.62509725, 1263.34010933,
       1461.34168646, 1554.01302019, 2173.65523126, 1625.91435308,
       1715.35422922, 1463.92313917, 1133.47220551, 2104.724202  ,
       1726.99163981, 1642.27763357, 1737.05792085, 1227.85585924,
       1036.32895404, 1343.6139518 , 2033.60429879, 2248.57280276,
       1490.13868345,  965.66717135, 1470.07722322, 2082.35284656,
       1402.81375879, 1629.191173  , 1013.9510897 , 1518.5332208 ,
       1173.1063004 , 2263.32956362, 1557.5492317 , 1788.37775053,
       1305.53854034, 1655.4323567 , 1632.70264996, 1404.10797388,
       2121.56671414,  999.79726666, 1399.2569939 , 1754.82722537,
       1359.41126819, 1613.31374504, 1475.58122398, 1540.92186925,
       2177.60354144, 3034.98974549, 2325.31055253, 1409.69064418,
       2237.65241167, 1515.62146119, 1249.95615401, 1748.27964179,
       2016.0136167 , 1957.10309093, 1452.2097767 , 1772.02097547,
       1137.16592633, 1629.31614114, 1167.91868432, 2348.63336955,
       1523.23773047, 1300.70886901, 1645.72403785, 1420.19215298,
       1444.66708706, 1436.76305024, 1099.94476579, 1701.8800249 ,
       2322.61458906, 1232.33437338, 1260.08023963, 1723.16137949,
       1887.70732612, 1701.81503607, 1790.83053268,  914.77649148,
       1696.6067957 , 1441.43912019, 1868.95073258, 1545.76983584,
       1550.57615605, 1806.28890615, 1792.8512335 , 1639.22174742,
       1532.31081012,  944.6324591 , 1694.40530218, 2112.75831971,
       1511.86067118, 1202.36348792, 1188.9711855 , 1170.56743184,
       1756.09312259, 1342.90959061, 1693.57923613, 1223.74552344,
       1165.39890303, 1468.00723594, 1432.59673335, 1916.58117106,
       1441.50097451, 1324.83970148, 1598.96990431, 2123.37367115,
       1795.99975421, 1210.3676503 , 1351.13560347, 2042.63866067,
       1742.33007137, 1653.10055672, 1160.62699911, 1910.81894455,
       1662.40362893, 1660.79083231, 1078.20161108,  972.7793312 ,
       1046.31590883, 1114.78822466, 2118.81475573, 1963.68472809,
       1231.22041707, 1529.95945772, 1704.38596502, 1697.92950405,
       1860.08129252, 1822.34997279, 1118.23248553, 1526.09035779,
       1632.41115894, 1213.90035197, 1565.73239007, 1291.86339435,
       1060.69645776, 1424.55473684, 1537.44174929, 1859.85793545,
       1255.50846078, 1516.42610263, 1755.15523015, 2576.04073817,
       1952.32035568, 1622.80227208, 1042.64740388, 1525.98001736,
       1463.64954008, 1472.8487372 , 1628.31401552, 1466.45131023,
       3012.35045875, 1615.65229978, 1754.36011222, 1281.58002687,
       1398.81498728, 1133.2937125 , 2028.35961751, 1245.75877301,
       1009.73849056, 2172.85416057, 1008.06032248, 1967.3729897 ,
       1399.91914027, 1977.6875883 , 1871.56855852, 1713.65132819,
       2431.03988768, 1674.24007688,  945.12465512, 1526.2981104 ,
       1628.33823393, 1677.09661026, 2979.97829   ,  946.09335596,
       1473.58054348, 1513.36073893, 1422.02042934, 1623.48398873,
       1195.43986627, 1255.08167629, 1763.17533179, 1151.50621583,
       1215.19529737, 2737.76465049, 1527.4347675 , 1753.06224722,
       1509.49634217, 1739.82288869, 1310.203044  , 1521.56582944,
       1471.63752792, 1576.18391689, 1446.98050982, 1299.73091306,
       1692.10644969, 1500.73332663, 1073.08428623, 1165.41230635,
        968.45384488, 2030.12541301, 1118.20961971, 2373.99115048,
        879.4840067 , 1576.29058057, 1515.13423237, 2180.65788307,
       1993.82743979, 1485.60855453, 2835.94092025, 2767.32987287,
       1588.53735828,  975.09076576, 1870.0239917 , 1037.24554929,
       1123.05709751, 1294.77070846, 1117.85354481, 1664.09501707,
       1595.38588389, 1092.12970848, 1057.14505548, 1451.11031929,
        927.17968257, 1673.32709516, 1847.16871887, 2628.73696356,
        857.13770759, 1391.64925378, 1039.85020974, 1714.27303736,
       1776.39045336, 1572.53017687, 1860.33491335, 1397.54339657,
       1546.90112199, 1494.85372597, 1280.87773586, 1379.63699956,
       1391.64754542, 1923.56087714, 1082.85341636, 2827.67807856,
       2002.30105218, 1097.2785562 , 1504.66213435, 1048.00666999,
       1135.23053507, 1325.7183516 , 1409.50471921, 1444.54101036,
       2208.39177569, 1120.48786861, 1412.48520169, 2129.78330563,
       1384.8947624 , 1617.83344485, 1545.54786569, 1319.91412252,
       1901.18719305, 2036.8455154 , 1059.34566352, 2170.12381557,
       1385.2898768 , 1333.53221871, 1963.94916   ,  984.88030606,
       1104.42950898, 1476.6633847 , 1876.68332397, 1785.69316893,
       1692.45879508, 1591.23971118, 1587.98280811, 1518.70824401,
       2832.81479632, 1442.29678472, 1717.63916503, 2672.35239593,
       1721.45638259, 2511.83991959, 1172.5248747 , 1883.45678035,
       1680.27597742, 1307.47593561, 2670.44148226, 1746.05954394,
       1649.31012957, 1700.01121712, 1338.28788837, 1316.87980076,
       1410.53986544, 1096.23864867, 1478.14994105, 1208.32450681,
       1900.24857587, 1292.78640707, 1505.87456038, 1557.7152852 ,
       1160.15887897,  936.21154289, 1482.72596905, 1213.80242289,
       1417.01570423, 1557.95721389, 1555.44926725, 1423.80852783,
       1281.40714425, 1644.64989876, 1119.38789783, 1980.1924535 ,
       1470.33256227, 1534.98723743, 2953.98007522, 1064.98746324,
       1340.41628032, 1425.09341938, 1399.25675638, 1576.29179531,
       1642.44814412, 1563.88171218, 1446.9559717 , 1826.7494948 ,
       1886.4977389 , 1064.49091876, 1798.0724041 , 1138.55560176,
       1405.99921364, 1350.18374801,  986.7196278 , 2011.32121755,
       2282.08013002, 2243.94216166, 1201.99017385, 1426.56901423,
       1481.06128931, 1288.40042301, 1072.7628699 , 1665.6428478 ,
       1884.97526171, 2596.31071766, 1327.39314616, 2760.99418461,
       1377.41572056, 1402.70207734, 1165.49218593, 1134.21216849,
       2013.38314708, 1400.67194415, 1812.06473155, 1952.67394719,
       1540.80521303,  925.68246631, 1487.14578556, 1945.35727256,
       2422.38012075, 1261.47146789, 2864.55647371, 2785.31907417,
        982.79606206, 1471.91617769, 1742.93436406, 1275.91234239,
       1021.59320182, 1800.07686666, 2307.59277451, 1595.42045885,
       1664.09025608, 1254.53481257, 1440.80324252, 1066.11822455,
       1949.97435603, 1128.94765213, 1843.40062946, 1740.03679872,
       1442.00717895, 1315.80068191, 1262.38919914, 2103.53777586,
       2136.55857803, 1582.46282254, 1187.60847266, 1262.83418506,
       1257.33738393, 1827.02279702, 1373.83437229, 1421.97644322,
       1702.97056749, 1046.97083701, 1270.77285826, 1384.20860069,
       1819.40648854, 2061.94681047, 1486.00268652, 1036.84260794,
       1647.84171804, 1635.42713123, 2351.22843416,  873.38383472,
       1721.94967539, 1477.86297074, 3224.29303311, 1728.88670988,
       1515.59375642, 1697.29785853, 1859.23113552, 1872.123478  ,
        899.92050959, 2794.70386417, 1824.40008989, 1824.53286078,
       1760.62433841, 1498.99894281, 2627.97344086, 1586.23138849,
       1588.78162587,  987.3762454 ,  904.02938319, 1758.60640127,
       2452.36026481, 1364.26677286, 1844.15635925, 1621.17006763,
       1452.0711698 , 1133.38457061, 1852.31891835, 1137.66510103,
       1746.26872344, 1345.82032178, 1556.50048343, 1211.68565744,
       1768.07249786, 1658.78162233, 1646.86197259, 1839.12504921,
       1280.68067122, 1456.92612896,  975.30693704, 1671.36593547,
       1350.73250023, 1643.3076417 , 1514.28489911, 2044.14804495,
       1403.97394072, 1794.70991723, 1464.90507308, 1420.3977016 ,
       1443.53706437, 1290.00154405, 1360.0059717 , 1330.1216173 ,
       1224.35725004, 1068.24815074, 1570.51740728, 1485.00410944,
       1166.29594271, 2245.67659585, 1230.23026473, 1414.42016352,
       1450.41568463, 1015.84485754, 1623.08087398, 1532.44947475,
       1559.65232906, 2893.71713067, 1089.88320372, 1510.31450842,
       1057.86028235, 1882.79751637, 2020.18941669, 1309.63909183,
       1329.46495065, 1555.61045926,  945.4273471 , 1933.88472921,
       1278.51088665, 1456.50229496, 1766.33546829, 1483.2442449 ,
       1343.24603078, 1338.40098414, 2047.68323715, 1554.41469654])

In [154]:
y_test2

1178    1635.0
865     1278.0
101     1764.0
439      924.0
58      2090.0
         ...
978     1725.0
1002    1048.0
509     1083.0
111     1987.0
226     1765.0
Name: price, Length: 960, dtype: float64

# polynomial regression